```dax
Saldo Projetado Final V9 = 
VAR _DataContexto = MAX ( 'dCalendário'[Date] )

// 1. Último dia realizado (mesma lógica)
VAR _UltimoDiaRealizado = 
    CALCULATE (
        MAX ( 'Base de Dados'[PAGTO] ), 
        'Base de Dados'[STATUS] IN { "Pago", "Recebido" },
        REMOVEFILTERS ( 'dCalendário' )
    )

// 2. Condição de saída
VAR _IsDataRealOuAnteriorOuSemBase = 
    ISBLANK ( _UltimoDiaRealizado ) || ( _DataContexto <= _UltimoDiaRealizado )

// 3. Último Saldo Real TOTAL (RECALCULADO IGNORANDO CONTEXTO)
VAR _UltimoSaldoReal = 
    IF( NOT _IsDataRealOuAnteriorOuSemBase, 
        VAR RelevantDate = _UltimoDiaRealizado
        // Cria uma tabela com dados relevantes até a data, removendo filtros indesejados
        VAR BaseTableFiltered = 
            CALCULATETABLE(
                'Base de Dados',
                'Base de Dados'[PAGTO] <= RelevantDate, // Acumula até a data
                'Base de Dados'[STATUS] IN {"Pago", "Recebido"}, // Apenas realizados
                ALL('Base de Dados'[FORN/CLIENTE]), // << Remove filtro FORN/CLIENTE
                ALL('Base de Dados'[EMPRESA]) // << Remove filtro EMPRESA (exemplo)
                // Adicione ALL() para outras colunas da Base de Dados se necessário
            )
        // Calcula o saldo líquido sobre a tabela filtrada
        RETURN
        SUMX(
            BaseTableFiltered,
            IF('Base de Dados'[GRUPO | DÉB CRÉD] = "ENTRADAS", 'Base de Dados'[REAL], -'Base de Dados'[REAL])
        )
    )

// 4. Calcular o ACUMULADO usando a tabela Resumo Projecao Diaria (mesma lógica V8)
VAR _NetProjetadoAcumulado = 
    IF( NOT _IsDataRealOuAnteriorOuSemBase, 
        CALCULATE(
            SUM('Resumo Projecao Diaria'[Valor Liquido Projetado Dia]),
            FILTER(
                ALL('dCalendário'[Date]),
                'dCalendário'[Date] > _UltimoDiaRealizado &&
                'dCalendário'[Date] <= _DataContexto
            )
        )
    )

// 5. Saldo Projetado Bruto
VAR _SaldoProjetadoCalculado = 
    IF( NOT _IsDataRealOuAnteriorOuSemBase, 
        _UltimoSaldoReal + COALESCE(_NetProjetadoAcumulado, 0)
    )

// 6. Tem transação no período?
VAR _TemTransacaoProjetadaNoPeriodo = 
    IF( NOT _IsDataRealOuAnteriorOuSemBase, 
        NOT(ISBLANK(_NetProjetadoAcumulado)),
        FALSE()
    )

// 7. RETURN final
RETURN
    IF (
        _IsDataRealOuAnteriorOuSemBase, 
        BLANK(),
        IF(
            _TemTransacaoProjetadaNoPeriodo, 
            _SaldoProjetadoCalculado, 
            _UltimoSaldoReal 
        )
    )
```
