```dax
Saldo Projetado Final V5 = 
VAR _DataContexto = MAX ( 'dCalendário'[Date] )

// 1. Determinar o último dia com transações REALIZADAS (Pago ou Recebido)
VAR _UltimoDiaRealizado = 
    CALCULATE (
        MAX ( 'Base de Dados'[PAGTO] ), 
        FILTER (
            ALL ( 'Base de Dados'[STATUS] ), 
            'Base de Dados'[STATUS] IN { "Pago", "Recebido" } 
        ),
        REMOVEFILTERS ( 'dCalendário' )
    )

// 2. Definir condição de saída: Se não há dia realizado ou a data atual é no passado/presente
VAR _IsDataRealOuAnteriorOuSemBase = 
    ISBLANK ( _UltimoDiaRealizado ) || ( _DataContexto <= _UltimoDiaRealizado )

// 3. Calcular variáveis de projeção APENAS se NÃO estivermos na condição de saída
VAR _UltimoSaldoReal = 
    IF( NOT _IsDataRealOuAnteriorOuSemBase, 
        CALCULATE (
            [Saldo Real Acumulado], 
            FILTER(
                ALL('dCalendário'), 
                'dCalendário'[Date] = _UltimoDiaRealizado
            )
        )
    )

// 4. Calcular o ACUMULADO de ENTRADAS projetadas (APENAS "Em aberto")
VAR _EntradasProjetadasAcumuladas = 
    IF( NOT _IsDataRealOuAnteriorOuSemBase, 
        CALCULATE (
            SUM ( 'Base de Dados'[REAL] ), 
            'Base de Dados'[VENCIMENTO] > _UltimoDiaRealizado,
            'Base de Dados'[VENCIMENTO] <= _DataContexto,    
            'Base de Dados'[STATUS] = "Em aberto", // AJUSTADO: Apenas "Em aberto"
            'Base de Dados'[GRUPO | DÉB CRÉD] = "ENTRADAS", 
            REMOVEFILTERS('dCalendário') 
        )
    )

// 5. Calcular o ACUMULADO de SAÍDAS projetadas (APENAS "Em aberto")
VAR _SaidasProjetadasAcumuladas = 
    IF( NOT _IsDataRealOuAnteriorOuSemBase, 
        CALCULATE (
            SUM ( 'Base de Dados'[REAL] ), 
            'Base de Dados'[VENCIMENTO] > _UltimoDiaRealizado,
            'Base de Dados'[VENCIMENTO] <= _DataContexto,    
            'Base de Dados'[STATUS] = "Em aberto", // AJUSTADO: Apenas "Em aberto"
            'Base de Dados'[GRUPO | DÉB CRÉD] = "SAÍDAS", 
            REMOVEFILTERS('dCalendário') 
        )
    )

// 6. Calcular o saldo projetado bruto (será BLANK se não for data futura)
VAR _SaldoProjetadoCalculado = 
    IF( NOT _IsDataRealOuAnteriorOuSemBase, 
        _UltimoSaldoReal + COALESCE(_EntradasProjetadasAcumuladas, 0) - COALESCE(_SaidasProjetadasAcumuladas, 0) 
    )

// 7. Verificar se houve transações projetadas ("Em aberto") NO PERÍODO TOTAL até a data atual
VAR _TemTransacaoProjetadaNoPeriodo = 
    IF( NOT _IsDataRealOuAnteriorOuSemBase, 
        NOT(ISBLANK(_EntradasProjetadasAcumuladas)) || NOT(ISBLANK(_SaidasProjetadasAcumuladas)),
        FALSE()
    )

// 8. RETURN final baseado nas variáveis pré-calculadas
RETURN
    IF (
        _IsDataRealOuAnteriorOuSemBase, 
        BLANK(),
        IF(
            _TemTransacaoProjetadaNoPeriodo, 
            _SaldoProjetadoCalculado, 
            _UltimoSaldoReal // Ou BLANK() se preferir não mostrar nada até a primeira projeção
        )
    )
```

**Explicação do Ajuste (V5):**

Conforme sua descoberta e solicitação, esta versão `Saldo Projetado Final V5` faz um único ajuste crucial:

*   **Filtro de Status:** Nas variáveis `_EntradasProjetadasAcumuladas` e `_SaidasProjetadasAcumuladas`, o filtro de status foi alterado de `'Base de Dados'[STATUS] IN { "Em aberto", "Atrasado" }` para `'Base de Dados'[STATUS] = "Em aberto"`.

Isso garante que apenas as transações futuras com status "Em aberto" sejam consideradas na projeção, excluindo as "Atrasado", o que deve resolver a diferença inicial de R$ 2.600,00 que você identificou.

Teste esta versão final.
